repos:
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.6
    hooks:
    -   id: forbid-crlf
    -   id: forbid-tabs
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v2.2.1
    hooks:
    -   id: trailing-whitespace
        files: ''
        args:
        - --no-markdown-linebreak-ext
    -   id: check-yaml
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v2.3.1
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
-   repo: git://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
-   repo: git://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
-   repo: local
    hooks:
    -   id: py.test
        name: py.test
        language: system
        entry: sh -c py.test
        files: ''
