-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.0.0
    hooks:
    -   id: forbid-crlf
    -   id: forbid-tabs
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 3fa02652357ff0dbb42b5bc78c673b7bc105fcf3
    hooks:
    -   id: trailing-whitespace
        files: ''
        args:
        - --no-markdown-linebreak-ext
    -   id: check-yaml
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: 4de6c8dfadef1a271a814561ce05b8bc1c446d22
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
-   repo: git://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.0.10
    hooks:
    -   id: python-safety-dependencies-check
-   repo: git://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.2
    hooks:
    -   id: python-bandit-vulnerability-check
-   repo: local
    hooks:
    -   id: py.test
        name: py.test
        language: system
        entry: sh -c py.test
        files: ''
