-   id: python-bandit-vulnerability-check
    name: bandit
    description: Python code vulnerabilities checker
    language: python
    types: [python]
    entry: bandit_analyzer
    args: [-lll, --recursive, .]
    always_run: true
    pass_filenames: false
