language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install -r dev-requirements.txt
# command to run tests
script: pre-commit install && pre-commit run --all-files
