name: CI

on:  # cf. https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} 🔧
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip 🏗️
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            ${{ runner.os }}-pip

      - name: Install ⚙️
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U -r dev-requirements.txt
          pip install -U .

      - name: Running checks ☑
        run:  pre-commit run --all-files --verbose
